//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Activity_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Classroom_Id { get; set; }
        public int School_Id { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Classroom Classroom1 { get; set; }
    }
}
